
package com.adarsh.jaxws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JaxWsFileServer", targetNamespace = "http://service.jaxws.adarsh.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface JaxWsFileServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.jaxws.adarsh.com/JaxWsFileServer/downloadRequest", output = "http://service.jaxws.adarsh.com/JaxWsFileServer/downloadResponse")
    public byte[] download(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.jaxws.adarsh.com/JaxWsFileServer/uploadFileRequest", output = "http://service.jaxws.adarsh.com/JaxWsFileServer/uploadFileResponse")
    public String uploadFile(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        byte[] arg1);

}
