
package com.adarsh.jaxws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JaxWsFileServerImplService", targetNamespace = "http://service.jaxws.adarsh.com/", wsdlLocation = "http://localhost:8080/JaxWsAttachmentMtomFileExample/fileService?wsdl")
public class JaxWsFileServerImplService
    extends Service
{

    private final static URL JAXWSFILESERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JAXWSFILESERVERIMPLSERVICE_EXCEPTION;
    private final static QName JAXWSFILESERVERIMPLSERVICE_QNAME = new QName("http://service.jaxws.adarsh.com/", "JaxWsFileServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JaxWsAttachmentMtomFileExample/fileService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JAXWSFILESERVERIMPLSERVICE_WSDL_LOCATION = url;
        JAXWSFILESERVERIMPLSERVICE_EXCEPTION = e;
    }

    public JaxWsFileServerImplService() {
        super(__getWsdlLocation(), JAXWSFILESERVERIMPLSERVICE_QNAME);
    }

    public JaxWsFileServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSFILESERVERIMPLSERVICE_QNAME, features);
    }

    public JaxWsFileServerImplService(URL wsdlLocation) {
        super(wsdlLocation, JAXWSFILESERVERIMPLSERVICE_QNAME);
    }

    public JaxWsFileServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSFILESERVERIMPLSERVICE_QNAME, features);
    }

    public JaxWsFileServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxWsFileServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JaxWsFileServer
     */
    @WebEndpoint(name = "JaxWsFileServerImplPort")
    public JaxWsFileServer getJaxWsFileServerImplPort() {
        return super.getPort(new QName("http://service.jaxws.adarsh.com/", "JaxWsFileServerImplPort"), JaxWsFileServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JaxWsFileServer
     */
    @WebEndpoint(name = "JaxWsFileServerImplPort")
    public JaxWsFileServer getJaxWsFileServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jaxws.adarsh.com/", "JaxWsFileServerImplPort"), JaxWsFileServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSFILESERVERIMPLSERVICE_EXCEPTION!= null) {
            throw JAXWSFILESERVERIMPLSERVICE_EXCEPTION;
        }
        return JAXWSFILESERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
