
package com.adarsh.jaxws.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyAuthenticationServiceImplService", targetNamespace = "http://ws.jaxws.adarsh.com/", wsdlLocation = "http://localhost:8080/JaxWsCredentialServer/helloworld?wsdl")
public class MyAuthenticationServiceImplService
    extends Service
{

    private final static URL MYAUTHENTICATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYAUTHENTICATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MYAUTHENTICATIONSERVICEIMPLSERVICE_QNAME = new QName("http://ws.jaxws.adarsh.com/", "MyAuthenticationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JaxWsCredentialServer/helloworld?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYAUTHENTICATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MYAUTHENTICATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MyAuthenticationServiceImplService() {
        super(__getWsdlLocation(), MYAUTHENTICATIONSERVICEIMPLSERVICE_QNAME);
    }

    public MyAuthenticationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYAUTHENTICATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public MyAuthenticationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MYAUTHENTICATIONSERVICEIMPLSERVICE_QNAME);
    }

    public MyAuthenticationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYAUTHENTICATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public MyAuthenticationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyAuthenticationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyAuthenticationService
     */
    @WebEndpoint(name = "MyAuthenticationServiceImplPort")
    public MyAuthenticationService getMyAuthenticationServiceImplPort() {
        return super.getPort(new QName("http://ws.jaxws.adarsh.com/", "MyAuthenticationServiceImplPort"), MyAuthenticationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyAuthenticationService
     */
    @WebEndpoint(name = "MyAuthenticationServiceImplPort")
    public MyAuthenticationService getMyAuthenticationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jaxws.adarsh.com/", "MyAuthenticationServiceImplPort"), MyAuthenticationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYAUTHENTICATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MYAUTHENTICATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MYAUTHENTICATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
