
package com.adarsh.jaxws.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyMessageWebServiceImplService", targetNamespace = "http://ws.jaxws.adarsh.com/", wsdlLocation = "http://localhost:8080/JaxWsSoapHandlerApplication/validator?wsdl")
@HandlerChain(file="handlers.xml")
public class MyMessageWebServiceImplService
    extends Service
{

    private final static URL MYMESSAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYMESSAGEWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MYMESSAGEWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.jaxws.adarsh.com/", "MyMessageWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JaxWsSoapHandlerApplication/validator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYMESSAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MYMESSAGEWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MyMessageWebServiceImplService() {
        super(__getWsdlLocation(), MYMESSAGEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public MyMessageWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYMESSAGEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public MyMessageWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MYMESSAGEWEBSERVICEIMPLSERVICE_QNAME);
    }

    public MyMessageWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYMESSAGEWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public MyMessageWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyMessageWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyMessageWebService
     */
    @WebEndpoint(name = "MyMessageWebServiceImplPort")
    public MyMessageWebService getMyMessageWebServiceImplPort() {
        return super.getPort(new QName("http://ws.jaxws.adarsh.com/", "MyMessageWebServiceImplPort"), MyMessageWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyMessageWebService
     */
    @WebEndpoint(name = "MyMessageWebServiceImplPort")
    public MyMessageWebService getMyMessageWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jaxws.adarsh.com/", "MyMessageWebServiceImplPort"), MyMessageWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYMESSAGEWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MYMESSAGEWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MYMESSAGEWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
