
package com.adarsh.jaxws.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerInfo", targetNamespace = "http://ws.jaxws.adarsh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerInfo {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://ws.jaxws.adarsh.com/", className = "com.adarsh.jaxws.ws.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://ws.jaxws.adarsh.com/", className = "com.adarsh.jaxws.ws.InitResponse")
    @Action(input = "http://ws.jaxws.adarsh.com/ServerInfo/initRequest", output = "http://ws.jaxws.adarsh.com/ServerInfo/initResponse")
    public void init();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "destroy", targetNamespace = "http://ws.jaxws.adarsh.com/", className = "com.adarsh.jaxws.ws.Destroy")
    @ResponseWrapper(localName = "destroyResponse", targetNamespace = "http://ws.jaxws.adarsh.com/", className = "com.adarsh.jaxws.ws.DestroyResponse")
    @Action(input = "http://ws.jaxws.adarsh.com/ServerInfo/destroyRequest", output = "http://ws.jaxws.adarsh.com/ServerInfo/destroyResponse")
    public void destroy();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIpAddress", targetNamespace = "http://ws.jaxws.adarsh.com/", className = "com.adarsh.jaxws.ws.GetIpAddress")
    @ResponseWrapper(localName = "getIpAddressResponse", targetNamespace = "http://ws.jaxws.adarsh.com/", className = "com.adarsh.jaxws.ws.GetIpAddressResponse")
    @Action(input = "http://ws.jaxws.adarsh.com/ServerInfo/getIpAddressRequest", output = "http://ws.jaxws.adarsh.com/ServerInfo/getIpAddressResponse")
    public String getIpAddress();

}
